### ISSUE TITLE
List of Food-Items

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/user-stories#1]
## Value Proposition

**As a** user

**I want** my food items to be displayed on a page

**in order to** get an overview of the food I have at home 

## Description

![image](https://user-images.githubusercontent.com/115499721/206713084-c3f89afd-1e0f-4b90-a915-013193bd3748.png)

## Acceptance Criteria

- [ ] Page shows a list of items
- [ ] items are displayed below each other
- [ ] Page has a header with title
- [ ] List can be scrolled down when there are many items

## Tasks

- [ ] Create branch for feature
- [ ] Create list component
- [ ] Create item component
- [ ] Create Header component
- [ ] Add dummy Data for items

**Comment by Elgin-Schultz** [comment]
That looks very convincing to me!

**Comment by ufelgen** [comment]
Hey Neele, das finde ich ist ein guter Einstieg :) mir ist gestern beim Maultaschen machen noch was eingefallen für deinen krassen Feature-Backlog ;) vielleicht noch ein Notizenfeld für Zubereitungs-/Kochzeit, wenn man die Lebensmittel aus der Originalverpackung rausgenommen hat? falls du das hilfreich findest, und dann noch Zeit ist :)

**Comment by NeeleWaehnke** [comment]
> Hey Neele, das finde ich ist ein guter Einstieg :) mir ist gestern beim Maultaschen machen noch was eingefallen für deinen krassen Feature-Backlog ;) vielleicht noch ein Notizenfeld für Zubereitungs-/Kochzeit, wenn man die Lebensmittel aus der Originalverpackung rausgenommen hat? falls du das hilfreich findest, und dann noch Zeit ist :)

gute Idee, ich schreib es mal auf meine Backlog-Ideensammlung :)

**Comment by julialoeschel** [comment]
Sehr gut! 
Wenn ich etwas anmerken müsste, dann wäre es die Darstellung im Scribble. 
Wenn Kästen um ein Textfeld gelegt werden (so wie bei best before und pcs) dann sieht es aus als wäre es ein Input Feld. 

Das könnte dein Team später verwirren. 
Ist wirklich nur eine Kleinigkeit, kannst du dir für später merken ;)
