### ISSUE TITLE
Add/Delete -Buttons

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/user-stories#2]
## Value Proposition

**As a** user

**I want to**  add and remove Items from the list

**to be able to** keep track of the food I have. 

## Description

![image](https://user-images.githubusercontent.com/115499721/206716145-5335282a-a056-475c-900c-d6475b937ac3.png)

## Acceptance Criteria

- [ ] Functional 'Add'-Button to create new Items
- [ ] Input fields for new Item require name and date
- [ ] Functional 'Remove'-Button to delete items
- [ ] Input field for date only accept date - format

## Tasks

- [ ] Add Buttons for create / delete item
- [ ] Write function for buttons that remove item from list/ add item to list
- [ ] Create input field for item name
- [ ] Create input field for item date
- [ ] create input field for item quantity
