### ISSUE TITLE
Separate Overview Page

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/user-stories#3]
## Value Proposition

**As a** user

**I want ** items that are close to the 'Best before' date to be highlighted and can be found on separate overview page

**to be able to** see which items I have to use soon

## Description

![image](https://user-images.githubusercontent.com/115499721/206725765-90e0ee8a-c45c-4138-a1e2-48e138a8060e.png)

## Acceptance Criteria

- [ ] Items look different when they are close to Best before date
- [ ] You can navigate to overview page
- [ ] navbar shows that there are items on overview page

## Tasks

- [ ] Create overview page for items that are close to their best before date
- [ ] Add navbar for navigate between list pages
- [ ] Add different styling for items that are close to best before date (e.g. background color, icon)
