### ISSUE TITLE
Edit items

### ISSUE THREAD

**Issue by NeeleWaehnke** [NeeleWaehnke/user-stories#5]
## Value Proposition

**As a** user

**I need** to be able to edit my items

**to be able to** correct typos, select new storage place or update quantity

## Description

![image](https://user-images.githubusercontent.com/115499721/206733930-b5c62c1e-6df1-4db7-a82f-96dcedff7db4.png)

## Acceptance Criteria

- [ ] each item has an edit icon
- [ ] when you click on edit button, item can be updated
- [ ] when item is edited a 'save changes' button is displayed
- [ ] after saving the item is shown with edited details

## Tasks

- [ ] add save and edit buttons to item card
- [ ] add function to 'save changes' button
- [ ] add function to 'edit' button
- [ ] display edited state of item
- [ ] style edit state of item
